### ISSUE TITLE
Time alignment (-T) doesn't work when saclist is provided

### ISSUE THREAD

**Issue by cuihaoleo** [seisman/GMT5-pssac#2]
It seems time alignment option doesn't work when saclist is provided instead of sac files.

sac files had been marked:

```
$ saclst t5 f data0 data1 
data0        16.13
data1        20.63
```

and my saclist:

```
cat list 
data0 0.000000 0.000000 0.5,black
data1 0.000000 0.000000 0.3,red
```

If I use `gmt pssac -JX20/20 -R0/100/-4/4 -T+t5 -M4 data* > output.ps` to plot, time axis is aligned by t5 as expected. But `gmt pssac -JX20/20 -R0/100/-4/4 -T+t5 -M4 list > output.ps` failed to align.

sac data files, saclist and every output ps file is uploaded for debugging:
[everything.zip](https://github.com/seisman/GMT5-pssac/files/313012/everything.zip)

**Comment by seisman** [comment]
GMT5-pssac is buggy, and still under development. 

Recently I am busy with other things, so I'm afraid I have no time to fix these bugs. If you'd like, you can help with the development.

**Comment by cuihaoleo** [comment]
Well, I've read part of the code, and it is clear that GMT5-pssac will use X-Y coordinate in the saclist and thus reset the alignment. I'll try to read original pssac code to find out its behaviour and the differences.

Also facing many exams these weeks :p
If not so busy in the summer holiday, I'm glad to participate with the development.

**Comment by seisman** [comment]
:smile:

**Comment by ghassan100** [comment]
Try using this list file. 

data0 0 0 1p,red 
data1 -4.5 0 1p,blue

Your x location of second file, is the difference between t5 of data0 minus t5 of data1

data0 16.13 
data1 20.63

**Comment by seisman** [comment]
@cuihaoleo Maybe it's not a bug, it's a feature.

The (X, Y) from saclist file always determine the location of the first point of each trace on plots.  This behavior is NOT compatible with the original pssac written by Prof. Lupei Zhu.

I am not sure whether I am making a right decision.
