### ISSUE TITLE
-v option with geographic map

### ISSUE THREAD

**Issue by ghassan100** [seisman/GMT5-pssac#3]
Great Code- I like it.
I have a problem  with -v option where stations are  close to each other and along a horizontal line,
see attached files including the script
<img width="533" alt="screen shot 2016-08-19 at 12 03 52 pm" src="https://cloud.githubusercontent.com/assets/19935980/17817649/2116b812-6605-11e6-8812-519fee6253bd.png">

The seismograms are plotted with changing  Y axis and keep almost the same value of X-axis. In another case where stations are distributed and distance between them is more than 70 km pssac with -v works fine. In case under consideration the interstation distance is less than 70 km. Thanks
script
gmt pssac SS_sac -P -v -Gp+gred+z0.1 -V -Fr -J$J -R$R -Bxa1f2 -Bya1f2  -BWSne -M1.0i -m5 -K -Wthinnest,blue > $ps
saclst stlo stla f SS_sac | awk '{print $2-0.05, $3}'| gmt psxy -J$J -R$R -St0.12i -Gblack -K -O >> $ps

Two images to show that -v option is not working as it suppose to be 
image 1 no -v
<img width="564" alt="screen shot 2016-08-19 at 1 31 47 pm" src="https://cloud.githubusercontent.com/assets/19935980/17820291/b6ae8e3e-6611-11e6-807f-0242a92f1d0a.png">
image 2 with -v option (station location is not where the signal begins. The plot is shifted from the station location

<img width="535" alt="screen shot 2016-08-19 at 1 32 01 pm" src="https://cloud.githubusercontent.com/assets/19935980/17820322/ddcbea2a-6611-11e6-820b-4490bd7b7816.png">

**Comment by seisman** [comment]
Fixed in c6d08073f1e97af3fcbcc475e155924bbe0c0ce0. Feel free to reopen the issue if the bug still exists.

**Comment by ghassan100** [comment]
Greetings Mr. Tian,

I thank you for taking the time and promptly fixing the -v issue. It seems the -G flag is no longer working with -v for geographic map.

Thanks,

Ghassan

**Comment by seisman** [comment]
Yes, it's a known and unfixed bug.

**Comment by seisman** [comment]
@ghassan100 The bug of -v and -G has been fixed. See `tests/test-geo.ps` and `tests/test-v.ps`.
